-- MySQL Script generated by MySQL Workbench
-- 11/22/15 09:29:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mytourism
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mytourism
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mytourism` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mytourism` ;

-- -----------------------------------------------------
-- Table `mytourism`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mytourism`.`user` (
  `userID` VARCHAR(5) NOT NULL COMMENT '',
  `userName` VARCHAR(20) NOT NULL COMMENT '',
  `firstName` VARCHAR(20) NOT NULL COMMENT '',
  `lastName` VARCHAR(20) NOT NULL COMMENT '',
  `password` VARCHAR(20) NOT NULL COMMENT '',
  `email` VARCHAR(60) NOT NULL COMMENT '',
  `NIC` VARCHAR(10) NOT NULL COMMENT '',
  `contactNo` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`userID`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `NIC_UNIQUE` (`NIC` ASC)  COMMENT '',
  UNIQUE INDEX `contactNo_UNIQUE` (`contactNo` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytourism`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mytourism`.`hotel` (
  `hotelID` VARCHAR(5) NOT NULL COMMENT '',
  `userID` VARCHAR(45) NULL COMMENT '',
  `hotelName` VARCHAR(100) NOT NULL COMMENT '',
  `hotelOwnerName` VARCHAR(45) NOT NULL COMMENT '',
  `city` VARCHAR(20) NOT NULL COMMENT '',
  `hotelAddress` VARCHAR(100) NOT NULL COMMENT '',
  `imagePath` VARCHAR(100) NULL COMMENT '',
  `Type` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`hotelID`)  COMMENT '',
  INDEX `FKeyForUSerTable_idx` (`userID` ASC)  COMMENT '',
  CONSTRAINT `FKeyForUSerTable`
    FOREIGN KEY (`userID`)
    REFERENCES `mytourism`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytourism`.`hotelroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mytourism`.`hotelroom` (
  `roomID` VARCHAR(5) NOT NULL COMMENT '',
  `hotelID` VARCHAR(5) NOT NULL COMMENT '',
  `roomType` VARCHAR(15) NOT NULL COMMENT '',
  `status` INT(1) NOT NULL DEFAULT 0 COMMENT '',
  `picture` VARCHAR(45) NULL COMMENT '',
  `price` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`roomID`, `hotelID`)  COMMENT '',
  CONSTRAINT `hotelIDFKey`
    FOREIGN KEY (`hotelID`)
    REFERENCES `mytourism`.`hotel` (`hotelID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytourism`.`bookingRooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mytourism`.`bookingRooms` (
  `roomID` VARCHAR(5) NOT NULL COMMENT '',
  `userID` VARCHAR(5) NOT NULL COMMENT '',
  `bookingDate` DATE NOT NULL COMMENT '',
  `checkInDate` DATE NOT NULL COMMENT '',
  `checkOutDate` DATE NOT NULL COMMENT '',
  INDEX `FkeyforroomId_idx` (`roomID` ASC)  COMMENT '',
  INDEX `FkeyForUserID_idx` (`userID` ASC)  COMMENT '',
  PRIMARY KEY (`roomID`, `userID`)  COMMENT '',
  CONSTRAINT `FkeyforroomId`
    FOREIGN KEY (`roomID`)
    REFERENCES `mytourism`.`hotelroom` (`roomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FkeyForUserID`
    FOREIGN KEY (`userID`)
    REFERENCES `mytourism`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
